### ISSUE TITLE
Validation errors not passed through to client

### ISSUE THREAD

**Issue by jefft** [sumoheavy/jira-ruby#102]
Hi,

Say I have a Required custom field, and attempt to create a JIRA issue without specifying it:

```
issue = client.Issue.build
issue.save({"fields"=>{"summary"=>"blarg from in example.rb","project"=>{"id"=>"12300"},"issuetype"=>{"id"=>"20"}}})
```

The error is highly cryptic: "Method Not Allowed":

```
/usr/local/lib/ruby/gems/2.1.0/gems/jira-ruby-0.1.13/lib/jira/request_client.rb:14:in `request': Method Not Allowed (JIRA::HTTPError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/jira-ruby-0.1.13/lib/jira/client.rb:159:in `request'
    from /usr/local/lib/ruby/gems/2.1.0/gems/jira-ruby-0.1.13/lib/jira/client.rb:138:in `get'
    from /usr/local/lib/ruby/gems/2.1.0/gems/jira-ruby-0.1.13/lib/jira/base.rb:339:in `fetch'
    from ./createtestpos.rb:13:in `<main>'
```

The real error message ("$field is required.") should be parsed out of the 400 response and returned.

**Comment by kenliu** [comment]
+1

**Comment by SimonMiaou** [comment]
As there is no activity for 2 years, I will close this one

**Comment by al-joshwilliams** [comment]
Well, sucks to be me then because I need this right now to troubleshoot.

**Comment by al-joshwilliams** [comment]
+1

Please reopen :(

**Comment by SimonMiaou** [comment]
@al-joshwilliams Could you help us and submit a PR?
