### ISSUE TITLE
Incorrect query params appended

### ISSUE THREAD

**Issue by beol** [sumoheavy/jira-ruby#107]
When trying to expand User resource, it fails because `url_with_query_params` method in `JIRA::Base` class doesn't take into account that the `url` parameter passed already has query params.

Calling `@jira_client.User.find('john', expand: 'groups')`, creates `/rest/api/2/user?username=john?expand=groups` which is incorrect and raised `JIRA::HTTPError`.

```
[llaksmana@llaksmana-ml:jira-ruby (branch_0.1.10)]$ irb
2.2.2 :001 > require_relative 'lib/jira'
 => true 
2.2.2 :002 > client = JIRA::Client.new(username: 'llaksmana', password: 'password', site: 'http://localhost:8080', context_path: '', auth_type: :basic, use_ssl: false)
 => #<JIRA::Client:0x007fe07a96bf88 @options={:site=>"http://localhost:8080", :context_path=>"", :rest_base_path=>"/rest/api/2", :ssl_verify_mode=>1, :use_ssl=>false, :auth_type=>:basic, :username=>"llaksmana", :password=>"password"}, @request_client=#<JIRA::HttpClient:0x007fe07a96be98 @options={:username=>"llaksmana", :password=>"password", :site=>"http://localhost:8080", :context_path=>"", :rest_base_path=>"/rest/api/2", :ssl_verify_mode=>1, :use_ssl=>false, :auth_type=>:basic}, @cookies={}>> 
2.2.2 :003 > client.User.find('llaksmana', expand: 'groups')
/rest/api/2/user?username=llaksmana
/rest/api/2/user?username=llaksmana?expand=groups
JIRA::HTTPError: JIRA::HTTPError
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/request_client.rb:14:in `request'
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/client.rb:155:in `request'
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/client.rb:134:in `get'
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/base.rb:339:in `fetch'
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/base.rb:110:in `find'
    from /Users/llaksmana/code/github/jira-ruby/lib/jira/base_factory.rb:33:in `block (2 levels) in delegate_to_target_class'
    from (irb):3
    from /Users/llaksmana/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```

**Comment by tholdaway-cs** [comment]
I ran into this also. Seems like this could be a pretty easy fix by making `url_with_query_params` parse its url argument with `URI` and append the new query params to the parsed query string or the `URI` object instead of just doing string concatenation.

**Comment by beol** [comment]
@tholdaway-cs I can't remember what I did exactly to patch this internally at work, but I think it's along the line what you just described.
