### ISSUE TITLE
`access_token': init_access_token must be called before using the client (JIRA::OauthClient::UninitializedAccessTokenError)

### ISSUE THREAD

**Issue by rojomisin** [sumoheavy/jira-ruby#113]
I am able to use `pry` interactive shell to create Jira issues using the jira-ruby gem.  But if I load this gem into a chef recipe, or just use it in a command line script (using basic_auth + SSL), it's throwing the error above.  How can I disable oauth and just use basicauth ?

stacktrace is

```
./jira-rfc-cli.rb 
/Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/oauth_client.rb:70:in `access_token': init_access_token must be called before using the client (JIRA::OauthClient::UninitializedAccessTokenError)
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/oauth_client.rb:79:in `make_request'
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/request_client.rb:13:in `request'
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/client.rb:159:in `request'
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/client.rb:148:in `post'
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/base.rb:351:in `save!'
        from /Users/rojomisin/.chefdk/gem/ruby/2.1.0/gems/jira-ruby-0.1.14/lib/jira/base.rb:365:in `save'
        from ./jira-rfc-cli.rb:93:in `<main>'

```

code is 

```
if createrfc then
  #do nothing
else
  ### send query
  query_create = {
      "fields" => {
          "summary" => "#{appname} deployment #{deploy_type} v#{buildnum} (#{env})",
          "project"=>{"id"=>"14599"},
          "issuetype"=>{"id"=>"8"},
          "customfield_10178"=>{"id"=>"10123"},
          "customfield_10172"=>{"id"=>"10136"},
          "customfield_10175"=>{"id"=>"10142"},
          "priority"=>{"id"=>"2"},
          "description"=> "#{desc}",
          "duedate"=>"#{simplenowdate}",
          "components" =>[ { "id" => "22106"} ]
      }
  }
  #save the data with the query
  ###create the RFC
  options = {
      'username'=>username,
      'password'=>password,
      'site'=>'https://jira.myhost.com',
      'context_path'=>'',
      'auth_type'=>'basic'
  }

  client = JIRA::Client.new(options)
  issue = client.Issue.build
  issue.save(query_create)
  if !issue.save(query_create) then
    err_issue = issue.to_json
  else
    success_issue = issue.attrs
    puts "#{success_issue['key']} created at #{success_issue['self']}"
    #### assign to someone as a separate step ####
    issue_url_assign = "#{success_issue['self']}/assignee"
    puts "#{issue_url_assign}"
    ### yuck
    assign = `curl -u '#{username}:#{password}' -X PUT --data '{"name": "#{username}"}' -H 'Content-Type: application/json' #{issue_url_assign}`
    puts "assignee output attempt = #{assign}"
  end

end
```

**Comment by rojomisin** [comment]
well looks like if I switched back to using symbols instead of strings things worked
```
  options = {
      :username => user,
      :password => pass,
      :site => jirasite,
      :context_path => '',
      :auth_type => :basic
  }
```

chef didn't like the symbols when i was trying to use the gem in a cookbook... if I have time later will try to get that working again
