### ISSUE TITLE
'require': cannot load such a file -- jira (LoadError) Driving me insane

### ISSUE THREAD

**Issue by Britaniola** [sumoheavy/jira-ruby#186]
Does anyone know what is going on here? I'm just trying to get Dashing running again but every time I start it, it crashes with this error:

```
/var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require': cannot load such file -- jira (LoadError)
        from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /home/skyhawk/dashboard/jobs/jira_number_of_issues_in_filter.rb:1:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
        from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing/app.rb:171:in `block in require_glob'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `each'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `require_glob'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing/app.rb:181:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
        from /var/lib/gems/2.1.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'
```

I've searched just about everywhere but I still can't find an answer, Please help!

BTW...config.ru:

```
require 'dashing'
require 'jira-ruby'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'
  set :outboard_file, 'https://dl.dropboxusercontent.com/s/huwfekrh7dupij9/outboard.txt'

  helpers do
    def protected!
     # Put any authentication code you want in here.
     # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

and, Gemfile:

```
source 'https://rubygems.org'

require 'json'
require 'jira-ruby'

gem 'dashing'
gem 'nokogiri'
gem 'htmlentities'
gem 'execjs', '2.0.2'
gem 'jira-ruby' , :require => 'jira'
gem 'therubyracer'
gem 'xml-simple'
gem 'google-api-client', '>=0.9.15'
gem 'google-drive'
gem 'roo'
gem 'omniauth-google-apps'
gem 'roo-google'
gem 'roo-xls'

## gem 'icalendar'
## gem 'rmagick'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.14.0'
```

Thanks

Bill

**Comment by bobbrodie** [comment]
@Britaniola You have `gem 'jira-ruby' , :require => 'jira'` in your Gemfile, however the library is no longer called "jira". This was cleaned up between 1.0.0 and 1.1.0, signaling a semver non-backwards compatible change. Try changing that line to `gem 'jira-ruby'` and see if that helps.

**Comment by SpookyFishes** [comment]
Hi, I have the same problem:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require': cannot load such file -- jira (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
        from c:/Daten/Wall-E/wallboard/jobs/sprint_progress.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing/app.rb:171:in `block in require_glob'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing/app.rb:170:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing/app.rb:170:in `require_glob'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing/app.rb:181:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing.rb:3:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/smashing-1.0.0/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from C:/Ruby23-x64/bin/thin:22:in `load'
        from C:/Ruby23-x64/bin/thin:22:in `<main>
```

I use 
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
jira-ruby (1.2.0)

Gemfile
```
source 'https://rubygems.org'

require 'jira-ruby'

gem 'smashing'
gem 'jira-ruby' 
```

config.ru
```
require 'dashing'
require 'jira-ruby'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'

  helpers do
    def protected!
      # Put any authentication code you want in here.
      # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

Do anybody have any idea to solve this problem?
Thanks in advance

**Comment by SpookyFishes** [comment]
I fixed my problem. In the job file was a require 'jira' this has to be renamed to require 'jira-ruby'.
