### ISSUE TITLE
Fetch Fails with Not Found if :site is not exactly right

### ISSUE THREAD

**Issue by kbaltrinic** [sumoheavy/jira-ruby#207]
I was attempting to follow the [create issue example](https://github.com/sumoheavy/jira-ruby/blob/3c91f0a03de9956604e8fe641d1f7949dadc6172/example.rb#L100) but kept getting Not Found errors on the fetch line as follows:

```
/home/.gems/gems/jira-ruby-1.1.3/lib/jira/request_client.rb:18:in `request': Not Found (JIRA::HTTPError)
	from /home/.gems/gems/jira-ruby-1.1.3/lib/jira/client.rb:213:in `request'
	from /home/.gems/gems/jira-ruby-1.1.3/lib/jira/client.rb:191:in `get'
	from /home/.gems/gems/jira-ruby-1.1.3/lib/jira/base.rb:339:in `fetch'
	from ../jira-client/test.rb:99:in `create_issue'
	from ../jira-client/test.rb:119:in `<main>'
```

I track the issue down to the [`sub()` invocation inside the url method of base.rb](https://github.com/sumoheavy/jira-ruby/blob/3c91f0a03de9956604e8fe641d1f7949dadc6172/lib/jira/base.rb#L431).  

My site was specified as 'https://my-stash-server:443/' and this did not match the value in 'self' which which lacked the port specification.  Another variation of the problem is with a server that accepts both http and https traffic.  In this case the protocol specifier in :site and in the 'self' attribute may not match.

**Comment by SimonMiaou** [comment]
@kbaltrinic Would you be ready to subit a PR in order to help us solve this issue?
