### ISSUE TITLE
Unable to update the status of the issue

### ISSUE THREAD

**Issue by manojrb** [sumoheavy/jira-ruby#236]
hi team,

   I am getting  Exception while trying to update the status of the issue.

/Users/manoj/.rvm/gems/ruby-2.3.0/gems/jira-ruby-1.2.0/lib/jira/request_client.rb:16:in `request': Internal Server Error (JIRA::HTTPError)
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/jira-ruby-1.2.0/lib/jira/client.rb:213:in `request'
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/jira-ruby-1.2.0/lib/jira/client.rb:201:in `post'
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/jira-ruby-1.2.0/lib/jira/base.rb:351:in `save!'
	from change_status.rb:16:in `<main>'

below code is used.

issue = client.Issue.find("250942")
issue_transition = issue.transitions.build
issue_transition.save!('transition' => {'id' => "3"})

Thanks in advance.

**Comment by arincon9** [comment]
@manojrb Were you ever able to solve this issue? Thanks in advance!

**Comment by rorykoehler** [comment]
Also experiencing this issue
