### ISSUE TITLE
Documentation is unclear about public key and the consumer key and is not working with Rails

### ISSUE THREAD

**Issue by beckah** [sumoheavy/jira-ruby#248]
Please feel free to close this, as it might just be me, but the documentation is super fuzzy about what to input as your private/public key for your Rails application.

I generated a public/private key as described:
`rake jira:generate_public_cert`

Which generated the following output:
```bash
Executing 'openssl req -x509 -nodes -newkey rsa:1024 -sha1 -keyout rsakey.pem -out rsacert.pem'
Generating a 1024 bit RSA private key
......++++++
.++++++
writing new private key to 'rsakey.pem'
-----
Done. The RSA-SHA1 private keyfile is in the current directory: 'rsakey.pem'.
You will need to copy the following certificate into your application link configuration in Jira:
-----BEGIN CERTIFICATE----- (This is obv fake)
Nullanecnullaelit.Sedmassamiullamcorperquisfringillaveldictumvitaeleo.
Vivamusvelultriciesmi.Duistempusfelisvelpharetracursus.Loremipsumd
olorsitametconsecteturadipiscingelit.Maurisvelitodiofringillaultricescon
sequateteleifendneclorem.Crasidurnametus.Crasvestibulumnullasedult
riceshendreritsemdoloraliquamnequesitametaccumsanquamaugueetnib
h.Vestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecub
iliaCurae;Seddictumturpismaurisnontinciduntduifermentumsitamet.Pell
entesquemollispellentesqueturpisutfringillamialiquetnec.Intinciduntmia
tvulputatetincidunt.Nullaaliqueteratvitaeexviverraquismattiseratlacinia.
Suspendissenisimassapharetraacturpisafermentumviverralectus=
-----END CERTIFICATE-----
```

I then generated the consumer key using
```
rake jira:generate_consumer_key
```

Which outputted 
```
You can use this as your consumer key: 9999999999999999999999999991
```

I then took that information and in my http://localhost:2990/plugins/servlet/applinks/listApplicationLinks I created a new link to my locally hosted rails app (localhost:3000)

My Jira's Outgoing Authentication > OAuth application link to my rails app looks like the following:
```
Status: Configured
Service Provider Name: rsacert.pem
Consumer Key: 9999999999999999999999999991
Shared Secret: Nullanecnullaelit.Sedmassamiullamcorperquisfringillaveldictumvitaeleo.Vivamusvelultriciesmi.Duistempusfelisvelpharetracursus.Loremipsumdolorsitametconsecteturadipiscingelit.Maurisvelitodiofringillaultricesconsequateteleifendneclorem.Crasidurnametus.Crasvestibulumnullasedultriceshendreritsemdoloraliquamnequesitametaccumsanquamaugueetnibh.VestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliaCurae;Seddictumturpismaurisnontinciduntduifermentumsitamet.Pellentesquemollispellentesqueturpisutfringillamialiquetnec.Intinciduntmiatvulputatetincidunt.Nullaaliqueteratvitaeexviverraquismattiseratlacinia.Suspendissenisimassapharetraacturpisafermentumviverralectus=
Request Token URL: /plugins/servlet/oauth/request-token
Access Token URL: /plugins/servlet/oauth/access-token
Authorize URL: /plugins/servlet/oauth/authorize
```
And I copied everything into my ApplicationController, IssuesController, and JiraSessionsController as prescribed.

So my **ApplicationsController** looks like:
```
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from JIRA::OauthClient::UninitializedAccessTokenError do
    redirect_to new_jira_session_url
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def get_jira_client

    # add any extra configuration options for your instance of JIRA,
    # e.g. :use_ssl, :ssl_verify_mode, :context_path, :site
    options = {
      :private_key_file => "rsakey.pem",
      :consumer_key => '9999999999999999999999999991'
    }

    @jira_client = JIRA::Client.new(options)

    # Add AccessToken if authorised previously.
    if session[:jira_auth]
      @jira_client.set_access_token(
        session[:jira_auth]['access_token'],
        session[:jira_auth]['access_key']
      )
    end
  end

end
```

My **JiraController** looks like:
```
class JiraSessionsController < ApplicationController

  before_action :get_jira_client

  def new
    callback_url = 'http://callback'
    request_token = @jira_client.request_token(oauth_callback: callback_url)
    session[:request_token] = request_token.token
    session[:request_secret] = request_token.secret

    redirect_to request_token.authorize_url
  end

  def authorize
    request_token = @jira_client.set_request_token(
      session[:request_token], session[:request_secret]
    )
    access_token = @jira_client.init_access_token(
      :oauth_verifier => params[:oauth_verifier]
    )

    session[:jira_auth] = {
      :access_token => access_token.token,
      :access_key => access_token.secret
    }

    session.delete(:request_token)
    session.delete(:request_secret)

    redirect_to projects_path
  end

  def destroy
    session.data.delete(:jira_auth)
  end
end
```

However, I'm still unable to authenticate my Jira instance. I get the following stacktrace:

```
OAuth::Unauthorized - 404 :
  oauth (0.5.3) lib/oauth/consumer.rb:236:in `token_request'
  oauth (0.5.3) lib/oauth/consumer.rb:155:in `get_request_token'
  jira-ruby (1.3.0) lib/jira/oauth_client.rb:48:in `request_token'
  app/controllers/jira_sessions_controller.rb:7:in `new'
  actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
  actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
  actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
  actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
  actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
  actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.3) lib/rack/etag.rb:25:in `call'
  rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.3) lib/rack/head.rb:12:in `call'
  rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
  actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
  web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
  rack (2.0.3) lib/rack/method_override.rb:22:in `call'
  rack (2.0.3) lib/rack/runtime.rb:22:in `call'
  activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
  rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
  railties (5.1.2) lib/rails/engine.rb:522:in `call'
  puma (3.9.1) lib/puma/configuration.rb:224:in `call'
  puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
  puma (3.9.1) lib/puma/server.rb:435:in `process_client'
  puma (3.9.1) lib/puma/server.rb:299:in `block in run'
  puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Definitely let me know if I'm doing something stupid, but from what I can tell when following the Rails portion of the documentation, I'm still unable to authenticate. 

Maybe it's how the oauth verifier isn't being handled?

I also tried add `:ssl_verify_mode    => OpenSSL::SSL::VERIFY_PEER` to my `options` with no luck and it rendered a 404.

My jira server is most definitely running. Additionally, I would love to do a PR in order to update the repo documentation once I can get this running. (before_filter is still being used in the docs so it looks like they could use an update)

**Comment by BrianAllenGit** [comment]
I'm currently having the same issue...

**Comment by beckah** [comment]
@SimonMiaou @malclocke @jamesmeador @wasabhi

**Comment by bobbrodie** [comment]
Hey everyone,

The rake task for generating the key is generally for running the tests in the CI environment. You wouldn't want to use this in your Rails application. I wouldn't say that's your issue, but just a note.

I'll run some tests on my end too, and check the latest docs to see if anything has changed https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/.

Thanks,
Bob

**Comment by beckah** [comment]
Oh, alright. Thank you so much for looking into it. Really appreciate it. @bobbrodie

**Comment by beckah** [comment]
@bobbrodie  Hi Bob, any updates? :) Thanks!

**Comment by bobbrodie** [comment]
I’ll keep the issue updated as the week moves forward.

**Comment by peterbell215** [comment]
The first thing I have to say is that I haven't used the OAuth2 functionality either in JIRA or via the jira-ruby library. 

One of the issues here is that we have a number of technologies that have to work in harmony (Rails, Pundit, jira-ruby) so the fact that the authorisation fails could be due to the way you are getting the technologies to interact rather than anything wrong in any one of the libraries.  I appreciate that is in effect what you are saying by your comments about the state of the documentation.

Personally, I would start by writing a standalone Ruby app that uses jira-ruby on its own with OAuth2 to get authenticated and then retrieves a JIRA.  a) you prove that jira-ruby's implementation of OAuth2 works with your JIRA's OAuth2 but b) you will also get a much better feeling for the jira-ruby library which will help you understand why it may not be working in the context of your Rails app.

As an aside, I have been developing a Devise strategy that will allow a Rails app to use jira-ruby and a JIRA to authenticate a username and password [(source here)](https://github.com/trapeze-bell-peter/devise-jira-authenticable).  This is very much WIP, and I only mention it as I ended up having to single step through a lot of the code in order to work out my mistakes.

Sorry, I can't be of more help.

**Comment by bobbrodie** [comment]
Alright, so I've been digging and have a little something, but am digging further. To be honest, the cert stuff was written a while before we took maintenance of the gem, and I've generally used the gem outside of Rails apps, in more of an ETL script type scenario to fill data for a microservice that had an API. That said, I'm working on getting a rails app running with the 2-way interface-based authentication on it.

I think that @peterbell215 's idea is great, authenticating outside of the gem, then you should be able to use the existing authorization to make calls. Personally, OAuth 2 has always thrown me off a bit, as each implementation isn't quite the same.

Back to the issue at hand, I was able to get certificate based calls to work in a test script. Here's what it looks like:

```
require 'jira-ruby'

options = {
  :site => 'http://localhost:2990',
  :context_path => '/jira',
  :private_key_file => 'rsakey.pem',
  :consumer_key => 'ff046b2942fda512a1cceea12b3bcf42'
}

client = JIRA::Client.new(options)

if ARGV.length == 0
  # If not passed any command line arguments, open a browser and prompt the
  # user for the OAuth verifier.
  request_token = client.request_token
  puts "Opening #{request_token.authorize_url}"
  system "open #{request_token.authorize_url}"

  puts "Enter the oauth_verifier: "
  oauth_verifier = gets.strip

  access_token = client.init_access_token(:oauth_verifier => oauth_verifier)
  puts "Access token: #{access_token.token} secret: #{access_token.secret}"
elsif ARGV.length == 2
  # Otherwise assume the arguments are a previous access token and secret.
  access_token = client.set_access_token(ARGV[0], ARGV[1])
else
  # Script must be passed 0 or 2 arguments
  raise "Usage: #{$0} [ token secret ]"
end

projects = client.Project.all

projects.each do |project|
  puts "Project -> key: #{project.key}, name: #{project.name}"
end
```

To get it working, follow these steps:

1. rake jira:generate_public_cert
2. rake jira:generate_consumer_key
3. Fire up a local instance of JIRA
4. Go to http://localhost:2990/jira/plugins/servlet/applinks/listApplicationLinks
5. Create a Non-Atlassian link, and enter the info on the Incoming Authentication tab. The consumer key will be the output of rake jira:generate_consumer_key, and the public key will be the contents of rsacert.pem.
6. Run the script above. When you run it without any parameters, it will open JIRA in a browser with OAuth authorization.
7. You'll want to click Allow. It will then give you a verification code - copy that.
8. Go back to your terminal and enter the verification code
9. You'll get the access token and secret, along with a list of projects

You can run the script again with 2 unnamed parameters (the access token and secret).

As for integrating with outbound OAuth 2, we'll need to keep digging. I believe that this will largely be up to the application, and JIRA's docs are a little fuzzy so we'll need some time.

Hopefully this demonstrates that calls out to JIRA work though, and can give some insight as to where things go in the JIRA admin.

**Comment by emwalker** [comment]
For anyone who is trying to get the oauth handshake to work in Rails and is running into this problem, which I was also running into, I got to the next step by replacing the parameters to the client that I was using with ones similar to the parameters from the previous comment:
```
options = {
  :site => 'http://localhost:2990',
  :context_path => '/jira',
  :private_key_file => 'rsakey.pem',
  :consumer_key => 'ff046b2942fda512a1cceea12b3bcf42'
}
```

Apparently there was a parameter that was causing problems.
