### ISSUE TITLE
saving attachments is broken because of incorrect arguments

### ISSUE THREAD

**Issue by gnowxilef** [sumoheavy/jira-ruby#314]
```
Traceback (most recent call last):
	quired)>'
	5: from /var/lib/gems/2.5.0/gems/methadone-2.0.1/lib/methadone/main.rb:167:in `go!'
	4: from /var/lib/gems/2.5.0/gems/methadone-2.0.1/lib/methadone/main.rb:398:in `call_main'
	3: from /var/lib/gems/2.5.0/gems/okta-x509-1.0.4/lib/okta/x509/app.rb:99:in `block in <module:App>'
	2: from /var/lib/gems/2.5.0/gems/okta-jira-1.3.2/lib/okta/jira/client.rb:273:in `upload_attachment'
	1: from /var/lib/gems/2.5.0/gems/jira-ruby-1.6.0/lib/jira/base.rb:361:in `save'
/var/lib/gems/2.5.0/gems/jira-ruby-1.6.0/lib/jira/resource/attachment.rb:22:in `save!': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by Guzmangm** [comment]
This should work:
```
#issue from ::Resource::Issue.jql
attachment = JIRA::Resource::Attachment.new client, issue: issue
attachment.save! "file" => file_path
```

**Comment by gnowxilef** [comment]
yep, that was it. forgot to close out the issue.
