### ISSUE TITLE
`request': No data received from server or forwarder (JIRA::HTTPError)

### ISSUE THREAD

**Issue by r3xling** [sumoheavy/jira-ruby#337]
code：

> options = {

    :username => config['Jira']['name'],
    :password => config['Jira']['pass'],
    :site => config['Jira']['site'],
    :auth_type => :basic,
    :use_ssl => false,
    :context_path => ''
}
client = JIRA::Client.new(options)
client.Project.all

error：
> Traceback (most recent call last):
	5: from *:in `<main>'
	4: from ～/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jira-ruby-1.7.0/lib/jira/base_factory.rb:31:in `block (2 levels) in delegate_to_target_class'
	3: from ～/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jira-ruby-1.7.0/lib/jira/base.rb:95:in `all'
	2: from ～/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jira-ruby-1.7.0/lib/jira/client.rb:220:in `get'
	1: from ～/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jira-ruby-1.7.0/lib/jira/client.rb:242:in `request'
～/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/jira-ruby-1.7.0/lib/jira/request_client.rb:15:in `request': No data received from server or forwarder (JIRA::HTTPError)

anybody help me？

**Comment by r3xling** [comment]
it's not about jira-ruby.
