### ISSUE TITLE
Load error with activesupport 7

### ISSUE THREAD

**Issue by orgads** [sumoheavy/jira-ruby#385]
See https://github.com/rails/rails/pull/43852
```
        27: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        26: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'

        25: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        24: from C:/Ruby/lib/ruby/gems/2.7.0/gems/jira-ruby-2.1.5/lib/jira-ruby.rb:8:in `<top (required)>'
        23: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        22: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'

        21: from C:/Ruby/lib/ruby/gems/2.7.0/gems/jira-ruby-2.1.5/lib/jira/base.rb:1:in `<top (required)>'
        20: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        19: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        18: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
        17: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        16: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        15: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
        14: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        13: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        12: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
        11: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        10: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         9: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
         8: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         7: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         6: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
         5: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         4: from C:/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         3: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
         2: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
         1: from C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
C:/Ruby/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
```

**Comment by pqtuan86** [comment]
Got the same issue here. To whom it may concern, please approve the PR. Thanks.
While waiting for the fix to be approved, any workaround @orgads ?

**Comment by orgads** [comment]
Yes.

```ruby
require 'active_support'
require 'jira-ruby'
```

**Comment by pqtuan86** [comment]
> Yes.
> 
> ```ruby
> require 'active_support'
> require 'jira-ruby'
> ```

Yeah, thought about it too, but thinking if this fix should be applied on `jira-ruby` gem or the its consumer.

**Comment by orgads** [comment]
It should be in jira-ruby. I opened PR #386 for that.

**Comment by SimonMiaou** [comment]
@orgads Thank you for the PR, will release it soon
