### ISSUE TITLE
Getting "undefined method `presence` for "Not Found":String" error when issue is not found

### ISSUE THREAD

**Issue by tory-kk** [sumoheavy/jira-ruby#432]
Hello, 
I am getting the following error when the issue is not found:

```
/home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/http_error.rb:11:in `initialize': undefined method `presence' for "Not Found":String (NoMethodError)

      @message = response.try(:message).presence || response.try(:body)
                                       ^^^^^^^^^
Did you mean?  presence_in
        from /home/user/Projects/Ruby-test/announce/jira_client.rb:13:in `exception'
        from /home/user/Projects/Ruby-test/announce/jira_client.rb:13:in `raise'
        from /home/user/Projects/Ruby-test/announce/jira_client.rb:13:in `request'
        from /home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/client.rb:306:in `request'
        from /home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/client.rb:279:in `get'
        from /home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/resource/issue.rb:95:in `fetch'
        from /home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/base.rb:107:in `find'
        from /home/user/bundler/ruby/3.2.0/gems/jira-ruby-2.3.0/lib/jira/base_factory.rb:31:in `block (2 levels) in delegate_to_target_class'
        from /home/user/Projects/Ruby-test/announce/jira_client.rb:54:in `get_issue'
```

Jira-ruby version: `2.3.0`.
Enabled `http_debug` and added logs:

```
get: /rest/api/2/issue/ABC-123?fields=summary%2Cstatus%2Cissuetype - []
RESPONSE: #<Net::HTTPNotFound:0x00007f603b8f3ac0>
```

Please advise on how it could be fixed.

**Comment by tory-kk** [comment]
> RESPONSE: #<Net::HTTPNotFound:0x00007f603b8f3ac0>
The response was successfully received and it was `NotFound`. 
The thing is that Jira returned HTTP status 404 and HTML page in the body (Content-Type `text/html`), so `HTTPError` construction fails.

**Comment by bobbrodie** [comment]
@tory-kk when using the latest version from my `master` branch, I'm seeing the intended behavior. Version 3.0.0 should be released shortly (I'm talking to a teammate tomorrow to approve some of my PRs so I don't self-approve) which will reflect this.

The most recent PR that touched on this specific issue is https://github.com/sumoheavy/jira-ruby/pull/435.

> Note: Loading `active_support/core_ext/object` modifies `to_json` output, so I have a PR to address the tests for the referenced PR.

My `Gemfile`:
```ruby
source 'https://rubygems.org'

gem 'jira-ruby', git: 'https://github.com/sumoheavy/jira-ruby', branch: 'master'
```

If you check out lib/jira/request_client.rb

```ruby
...
# Returns the response if the request was successful (HTTP::2xx) and
# raises a JIRA::HTTPError if it was not successful, with the response
# attached.

def request(*args)
  response = make_request(*args)
  raise HTTPError, response unless response.is_a?(Net::HTTPSuccess)
  response
end
...
```

And here's my response when requesting an issue that doesn't exist:

```
/path/to/local/gem/jira-ruby/lib/jira/request_client.rb:13:in `request': Not Found (JIRA::HTTPError)
	from /Users/robert/Projects/opensource/jira-ruby/lib/jira/client.rb:306:in `request'
	from /Users/robert/Projects/opensource/jira-ruby/lib/jira/client.rb:279:in `get'
	from /Users/robert/Projects/opensource/jira-ruby/lib/jira/resource/issue.rb:95:in `fetch'
	from /Users/robert/Projects/opensource/jira-ruby/lib/jira/base.rb:107:in `find'
	from /Users/robert/Projects/opensource/jira-ruby/lib/jira/base_factory.rb:31:in `block (2 levels) in delegate_to_target_class'
	from jira.rb:22:in `<main>'
```

When I request an issue that doesn't exist, I am receiving an `HTTPError` as expected.

**Comment by keegangroth** [comment]
For anyone else who finds this before it's released, I was able to work around this by using the require from the previously linked #435 after I required this gem. Like so:
```
require 'jira-ruby'
require 'active_support/core_ext/object'
```
